Update postgres-test.yml

diff --git a/.github/workflows/postgres-test.yml b/.github/workflows/postgres-test.yml
--- a/.github/workflows/postgres-test.yml
+++ b/.github/workflows/postgres-test.yml
@@ -1,3 +1,165 @@
+# name: Postgres ERP Test
+# on:
+#   push:
+#     branches:
+#       - pre-prod
+#   pull_request:
+# concurrency:
+#   group: postgres-erp-${{ github.event.number }}
+#   cancel-in-progress: true
+# jobs:
+#   tests:
+#     runs-on: ubuntu-latest
+#     strategy:
+#       fail-fast: false
+#     name: Server
+#     services:
+#       redis-cache:
+#         image: redis:alpine
+#         ports:
+#           - 13000:6379
+#       redis-queue:
+#         image: redis:alpine
+#         ports:
+#           - 11000:6379
+#       postgres:
+#         image: postgres:13
+#         env:
+#           POSTGRES_USER: postgres
+#           POSTGRES_PASSWORD: root
+#           POSTGRES_DB: test_site
+#         ports:
+#           - 5432:5432
+#         options: --health-cmd="pg_isready -U root" --health-interval=5s --health-timeout=2s --health-retries=3
+#     steps:
+#       - name: Clone
+#         uses: actions/checkout@v3
+#       - name: Setup Python
+#         uses: actions/setup-python@v4
+#         with:
+#           python-version: '3.10'
+#       - name: Setup Node
+#         uses: actions/setup-node@v3
+#         with:
+#           node-version: 18
+#           check-latest: true
+#       - name: Cache pip
+#         uses: actions/cache@v2
+#         with:
+#           path: ~/.cache/pip
+#           key: ${{ runner.os }}-pip-${{ hashFiles('**/*requirements.txt', '**/pyproject.toml', '**/setup.py', '**/setup.cfg') }}
+#           restore-keys: |
+#             ${{ runner.os }}-pip-
+#             ${{ runner.os }}-
+#       - name: Get yarn cache directory path
+#         id: yarn-cache-dir-path
+#         run: 'echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT'
+#       - uses: actions/cache@v3
+#         id: yarn-cache
+#         with:
+#           path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
+#           key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
+#           restore-keys: |
+#             ${{ runner.os }}-yarn-
+#       - name: Install PostgreSQL Client
+#         run: sudo apt-get install postgresql-client
+#       - name: Install Redis Server
+#         run: sudo apt-get install redis-server -y
+     
+#       - name: Setup
+#         run: |
+#           pip3 install frappe-bench
+#           bench init --skip-redis-config-generation --skip-assets --python "$(which python)" --frappe-path https://github.com/8848digital/frappe-v15.git --frappe-branch pre-prod ~/frappe-bench
+
+          
+
+#       # - name: Setup Frappe
+#       #   working-directory: /home/runner/frappe-bench
+#       #   run: |
+#       #     bench init frappe-bench --frappe-path https://github.com/8848digital/frappe-v15.git --frappe-branch pre-prod 
+      
+#       - name: Install
+#         working-directory: /home/runner/frappe-bench
+#         run: |
+#           bench get-app erpnext https://github.com/nirav8848/erpnext.git --branch pre-prod
+#           bench get-app https://itananddigital:${{secrets.GH_PAT}}@github.com/8848digital/ERPNext-India.git --branch pre-prod
+#           bench get-app https://github.com/nirav8848/india_compliance.git --branch pre-prod
+#           bench get-app https://github.com/8848digital/Assets --branch pre-prod
+#           bench get-app https://itananddigital:${{secrets.GH_PAT}}@github.com/8848digital/CRM --branch pre-prod
+#           bench get-app https://itananddigital:${{secrets.GH_PAT}}@github.com/8848digital/projects.git --branch pre-prod
+#           bench get-app https://itananddigital:${{secrets.GH_PAT}}@github.com/8848digital/sales_commission.git --branch pre-prod
+#           bench get-app --branch version-15 payments
+#           bench setup requirements --dev
+#           bench new-site --db-type postgres --db-root-password root --admin-password admin test_site
+#           bench --site test_site install-app erpnext
+#           bench --site test_site install-app erpnext_india
+#           bench --site test_site install-app assets
+#           bench --site test_site install-app crm
+#           bench --site test_site install-app projects
+#           bench --site test_site install-app payments
+#           bench --site test_site install-app sales_commission
+#           bench --site test_site install-app india_compliance
+          
+          
+#         env:
+#           CI: 'Yes'
+#   #    - name: Run Tests
+#       #  working-directory: /home/runner/frappe-bench
+#      #   run: |
+#        #   bench --site test_site set-config allow_tests true
+#        #   bench --site test_site run-tests 
+#       #  env:
+#     #      TYPE: server
+#       # - name: Run Tests
+#       #   run: cd ~/frappe-bench/ && bench --site test_site run-tests --app erpnext  --coverage  || echo "Tests completed with errors, but proceeding..."
+#       #   env:
+#       #     TYPE: server
+
+#       # - name: Run Tests
+#       #   run: |
+#       #     cd ~/frappe-bench/ && bench --site test_site run-tests --app erpnext --coverage 2>&1 | tee test_output.log || echo "Tests completed with errors, but proceeding..." grep -v "doctype" test_output.log > filtered_test_output.log || true
+#       #   env:
+#       #     TYPE: server
+
+#       # - name: Run Tests
+#       #   run: |
+#       #     set +e  # Prevents script from exiting on error
+#       #     cd ~/frappe-bench/
+#       #     bench --site test_site run-tests --app erpnext --coverage 2>&1 | tee test_output.log
+#       #     echo "Tests completed, proceeding with next steps..."
+#       #   env:
+#       #     TYPE: server
+
+      
+
+
+#       - name: Run Tests
+#         working-directory: /home/runner/frappe-bench
+#         run: |
+#           bench --site test_site set-config developer_mode 1
+#           bench --site test_site set-config allow_tests true
+#           bench --site test_site run-tests --app erpnext  --coverage  || echo "Tests completed with errors, but proceeding..."
+#         env:
+#           TYPE: server
+     
+
+
+          
+#       - name: Upload coverage data
+#         uses: codecov/codecov-action@v5
+#         with:
+#           fail_ci_if_error: false
+#           files: /home/runner/frappe-bench/sites/coverage.xml
+#           verbose: true
+#           token: ${{ secrets.CODECOV_TOKEN }}
+
+
+#       - name: Upload coverage data
+#         uses: actions/upload-artifact@v4
+#         with:
+#           name: coverage-
+#           path: /home/runner/frappe-bench/sites/coverage.xml
+
 name: Postgres ERP Test
 on:
   push:
@@ -30,55 +192,48 @@ jobs:
           POSTGRES_DB: test_site
         ports:
           - 5432:5432
-        options: --health-cmd="pg_isready -U root" --health-interval=5s --health-timeout=2s --health-retries=3
+        options: >-
+          --health-cmd="pg_isready -U postgres"
+          --health-interval=5s
+          --health-timeout=2s
+          --health-retries=3
     steps:
-      - name: Clone
+      - name: Clone Repository
         uses: actions/checkout@v3
       - name: Setup Python
         uses: actions/setup-python@v4
         with:
           python-version: '3.10'
-      - name: Setup Node
+      - name: Setup Node.js
         uses: actions/setup-node@v3
         with:
           node-version: 18
           check-latest: true
-      - name: Cache pip
+      - name: Cache Dependencies (PIP)
         uses: actions/cache@v2
         with:
           path: ~/.cache/pip
-          key: ${{ runner.os }}-pip-${{ hashFiles('**/*requirements.txt', '**/pyproject.toml', '**/setup.py', '**/setup.cfg') }}
+          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/pyproject.toml', '**/setup.py', '**/setup.cfg') }}
           restore-keys: |
             ${{ runner.os }}-pip-
             ${{ runner.os }}-
-      - name: Get yarn cache directory path
-        id: yarn-cache-dir-path
-        run: 'echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT'
-      - uses: actions/cache@v3
+      - name: Cache Dependencies (Yarn)
         id: yarn-cache
+        uses: actions/cache@v3
         with:
-          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
-          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
+          path: ~/.yarn-cache
+          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
           restore-keys: |
-            ${{ runner.os }}-yarn-
-      - name: Install PostgreSQL Client
-        run: sudo apt-get install postgresql-client
-      - name: Install Redis Server
-        run: sudo apt-get install redis-server -y
-     
-      - name: Setup
+            yarn-${{ runner.os }}-
+      - name: Install Dependencies
         run: |
-          pip3 install frappe-bench
+          sudo apt-get update
+          sudo apt-get install -y postgresql-client redis-server
+      - name: Install Frappe Bench
+        run: |
+          pip install frappe-bench
           bench init --skip-redis-config-generation --skip-assets --python "$(which python)" --frappe-path https://github.com/8848digital/frappe-v15.git --frappe-branch pre-prod ~/frappe-bench
-
-          
-
-      # - name: Setup Frappe
-      #   working-directory: /home/runner/frappe-bench
-      #   run: |
-      #     bench init frappe-bench --frappe-path https://github.com/8848digital/frappe-v15.git --frappe-branch pre-prod 
-      
-      - name: Install
+      - name: Install Apps
         working-directory: /home/runner/frappe-bench
         run: |
           bench get-app erpnext https://github.com/nirav8848/erpnext.git --branch pre-prod
@@ -90,6 +245,9 @@ jobs:
           bench get-app https://itananddigital:${{secrets.GH_PAT}}@github.com/8848digital/sales_commission.git --branch pre-prod
           bench get-app --branch version-15 payments
           bench setup requirements --dev
+      - name: Create Site
+        working-directory: /home/runner/frappe-bench
+        run: |
           bench new-site --db-type postgres --db-root-password root --admin-password admin test_site
           bench --site test_site install-app erpnext
           bench --site test_site install-app erpnext_india
@@ -99,62 +257,35 @@ jobs:
           bench --site test_site install-app payments
           bench --site test_site install-app sales_commission
           bench --site test_site install-app india_compliance
-          
-          
-        env:
-          CI: 'Yes'
-  #    - name: Run Tests
-      #  working-directory: /home/runner/frappe-bench
-     #   run: |
-       #   bench --site test_site set-config allow_tests true
-       #   bench --site test_site run-tests 
-      #  env:
-    #      TYPE: server
-      # - name: Run Tests
-      #   run: cd ~/frappe-bench/ && bench --site test_site run-tests --app erpnext  --coverage  || echo "Tests completed with errors, but proceeding..."
-      #   env:
-      #     TYPE: server
-
-      # - name: Run Tests
-      #   run: |
-      #     cd ~/frappe-bench/ && bench --site test_site run-tests --app erpnext --coverage 2>&1 | tee test_output.log || echo "Tests completed with errors, but proceeding..." grep -v "doctype" test_output.log > filtered_test_output.log || true
-      #   env:
-      #     TYPE: server
-
-      # - name: Run Tests
-      #   run: |
-      #     set +e  # Prevents script from exiting on error
-      #     cd ~/frappe-bench/
-      #     bench --site test_site run-tests --app erpnext --coverage 2>&1 | tee test_output.log
-      #     echo "Tests completed, proceeding with next steps..."
-      #   env:
-      #     TYPE: server
-
-      
-
-
-      - name: Run Tests
+      - name: Set Permissions & Configs
         working-directory: /home/runner/frappe-bench
         run: |
           bench --site test_site set-config allow_tests true
-          bench --site test_site run-tests --app erpnext  --coverage  || echo "Tests completed with errors, but proceeding..."
+          bench --site test_site set-config developer_mode 1
+          bench --site test_site set-config db_host localhost
+          bench --site test_site set-config admin_password admin
+      - name: Run Tests
+        working-directory: /home/runner/frappe-bench
+        run: |
+          set +e  # Prevent script exit on failure
+          bench --site test_site run-tests --app erpnext --coverage 2>&1 | tee test_output.log
+          echo "Tests completed, proceeding with next steps..."
         env:
           TYPE: server
-     
-
-
-          
-      - name: Upload coverage data
+      - name: Upload Coverage Data to Codecov
         uses: codecov/codecov-action@v5
         with:
           fail_ci_if_error: false
           files: /home/runner/frappe-bench/sites/coverage.xml
           verbose: true
           token: ${{ secrets.CODECOV_TOKEN }}
-
-
-      - name: Upload coverage data
+      - name: Upload Coverage Data as Artifact
         uses: actions/upload-artifact@v4
         with:
-          name: coverage-
+          name: coverage
           path: /home/runner/frappe-bench/sites/coverage.xml
+      - name: Upload Test Logs
+        uses: actions/upload-artifact@v4
+        with:
+          name: test-logs
+          path: /home/runner/frappe-bench/test_output.log
