Update postgres-test.yml

diff --git a/.github/workflows/postgres-test.yml b/.github/workflows/postgres-test.yml
--- a/.github/workflows/postgres-test.yml
+++ b/.github/workflows/postgres-test.yml
@@ -65,10 +65,19 @@ jobs:
         run: sudo apt-get install postgresql-client
       - name: Install Redis Server
         run: sudo apt-get install redis-server -y
+     
       - name: Setup
         run: |
           pip3 install frappe-bench
           bench init --skip-redis-config-generation --skip-assets --python "$(which python)" --frappe-path https://github.com/8848digital/frappe-v15.git --frappe-branch pre-prod ~/frappe-bench
+
+          
+
+      # - name: Setup Frappe
+      #   working-directory: /home/runner/frappe-bench
+      #   run: |
+      #     bench init frappe-bench --frappe-path https://github.com/8848digital/frappe-v15.git --frappe-branch pre-prod 
+      
       - name: Install
         working-directory: /home/runner/frappe-bench
         run: |
@@ -86,23 +95,49 @@ jobs:
           bench --site test_site install-app projects
           bench --site test_site install-app payments
           bench --site test_site install-app sales_commission
+          
+          
         env:
           CI: 'Yes'
-      - name: Set Administrator Role for Test User
-        working-directory: /home/runner/frappe-bench
-        run: |
-          bench --site test_site execute frappe.core.doctype.user.user.create_user --args '["test@example.com", "Test User", "password"]'
-          bench --site test_site execute frappe.core.doctype.user.user.add_role --args '["test@example.com", "Administrator"]'
-          bench --site test_site execute frappe.core.doctype.user.user.save --args '["test@example.com"]'
-        env:
-          TYPE: server
-      - name: Run Tests as Administrator
+  #    - name: Run Tests
+      #  working-directory: /home/runner/frappe-bench
+     #   run: |
+       #   bench --site test_site set-config allow_tests true
+       #   bench --site test_site run-tests 
+      #  env:
+    #      TYPE: server
+      # - name: Run Tests
+      #   run: cd ~/frappe-bench/ && bench --site test_site run-tests --app erpnext  --coverage  || echo "Tests completed with errors, but proceeding..."
+      #   env:
+      #     TYPE: server
+
+      # - name: Run Tests
+      #   run: |
+      #     cd ~/frappe-bench/ && bench --site test_site run-tests --app erpnext --coverage 2>&1 | tee test_output.log || echo "Tests completed with errors, but proceeding..." grep -v "doctype" test_output.log > filtered_test_output.log || true
+      #   env:
+      #     TYPE: server
+
+      # - name: Run Tests
+      #   run: |
+      #     set +e  # Prevents script from exiting on error
+      #     cd ~/frappe-bench/
+      #     bench --site test_site run-tests --app erpnext --coverage 2>&1 | tee test_output.log
+      #     echo "Tests completed, proceeding with next steps..."
+      #   env:
+      #     TYPE: server
+
+
+      - name: Run Tests
         working-directory: /home/runner/frappe-bench
         run: |
           bench --site test_site set-config allow_tests true
-          bench --site test_site run-tests --app erpnext --coverage --user test@example.com || echo "Tests completed with errors, but proceeding..."
+          bench --site test_site run-tests --app erpnext  --coverage  || echo "Tests completed with errors, but proceeding..."
         env:
           TYPE: server
+     
+
+
+          
       - name: Upload coverage data
         uses: codecov/codecov-action@v5
         with:
@@ -110,6 +145,8 @@ jobs:
           files: /home/runner/frappe-bench/sites/coverage.xml
           verbose: true
           token: ${{ secrets.CODECOV_TOKEN }}
+
+
       - name: Upload coverage data
         uses: actions/upload-artifact@v4
         with:
